### ISSUE TITLE
not showing up on latest xcode 

### ISSUE THREAD

**Issue by S0U1SB4N3** [StevenMagdy/CarboNow4Xcode#1]
![Screen Shot 2019-08-23 at 1 17 11 PM](https://user-images.githubusercontent.com/22788570/63610845-6ae3c380-c5a8-11e9-9ecc-75fca00c75de.png)
this is after install on most updated xcode 12.4 support version 10.3
![Screen Shot 2019-08-23 at 1 18 29 PM](https://user-images.githubusercontent.com/22788570/63610884-85b63800-c5a8-11e9-808f-3a0232283a57.png)

**Comment by StevenSorial** [comment]
Working on my Xcode 10.3, so maybe its not a version problem.
Try This

1. Close Xcode Completely
2. Open macOS Preferences -> Extensions
3. Select 'Xcode Source Editor' extensions
4. Uncheck then check carbon-now-sh
5. Open Xcode and try again

Let me know if it didn't work :)
