### ISSUE TITLE
Does not work on Xcode 12

### ISSUE THREAD

**Issue by L1cardo** [StevenMagdy/CarboNow4Xcode#2]

**Comment by StevenSorial** [comment]
Are you running macOS Big Sur?

**Comment by L1cardo** [comment]
> Are you running macOS Big Sur?

I am on
macOS Big Sur 11.0 (20A5384c)
Xcode Version 12.0.1 (12A7300)

**Comment by StevenSorial** [comment]
That will do it. Xcode extensions must be rebuilt with Xcode 12 to work on Big Sur. I will upload a new build in the coming days.

**Comment by StevenSorial** [comment]
@L1cardo Uploaded a new version. please let me know if it doesn't work for you.

**Comment by L1cardo** [comment]
> @L1cardo Uploaded a new version. please let me know if it doesn't work for you.

Works perfect now！ 
Thanks!
